export const NIAGRA = '#0aaca0'
export const FOAM = '#C9EDEA'
export const DALI = '#36BBB1'
export const WHITE = '#FFF'
export const ALABASTER = '#F8F8F8'
export const RICE_CAKE = '#F3F3F3'
export const LILAC = '#E8E8E8'
